$ANSIBLE_VAULT;1.1;AES256
66303738333532313762623262653835313936333530323764323761616666643833306635636463
6462643731373734643636633665646532613835363235660a303863303435393065613737636361
66323663633033366139373265383838633931626639363461376434643633643333636138623061
3866616138653731310a623932333732373935626663626534663936616434333838356139356339
34393836313639303336373961356339313836616261663335343936323639366233
